### PR TITLE
Fixes missing implicit return in example in README

### PR DESCRIPTION
**Pull request by lourd**

### CODE REVIEW

**Comment by GitCop** [comment]
:warning: Pull Request - Issues :warning:

 * Commit: 69327a502bb64b6ab71877ed07c666b100ac684a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**



---
This message was auto-generated by https://gitcop.com

**Comment by ertrzyiks** [comment]
@lourd Good catch, that makes sense. We have a bunch of `(ctx) => {`, would you mind update them all?

**Comment by michael-ciniawsky** [comment]
Any update on this? :)

**Comment by lourd** [comment]
Thanks for the ping. I'll add the other fixes now

**Comment by GitCop** [comment]
:warning: Pull Request - Issues :warning:

 * Commit: 443e1b46dbd70f4b29a91adcb4adb9c1cf0a55c8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**



---
This message was auto-generated by https://gitcop.com

**Comment by lourd** [comment]
Should be good to go now

**Comment by michael-ciniawsky** [comment]
👍  pls rebase -> docs(README): {{ message }} and add ourself to contriutors in README and package.json

**Comment by michael-ciniawsky** [comment]
you're fast 😛

**Comment by michael-ciniawsky** [comment]
I can add you in the next release aswell your prefence

**Comment by lourd** [comment]
Thanks for the offer to note me as a contributor 🙂 Since it's just tiny docs edits I'll forego being listed as a contributor, though.

**Comment by michael-ciniawsky** [comment]
yep kk I understand :) , it's just natural here that ever PR gets listed as Contributor, I do it within the next release. If you have something against being mentioned at all, please let me know. 
 
Thx 👍

**Comment by lourd** [comment]
Nope, not against it. Cheers 👊🏼

**Comment by michael-ciniawsky** [comment]
:+1:

**Pull request merged**
