### PR TITLE
feat: support for postcss 8 plugins

### LINKED ISSUE #199: PostCSS 8 support
[PostCSS 8.0 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0)

- [ ] Plugin now can be an object with `plugin.postcssPlugin` key

### PR DESCRIPTION
**Pull request by m4thieulavoie**
### `Notable Changes`

This PR is aiming to support postcss 8 plugins. Not sure if I cover everything in there, or if I should be adding any additional tests

#### `Commit Message Summary (CHANGELOG)`
Support for postcss 8 plugins
```
feat: support for postcss 8 plugins
```

### `Type`

- [x] Feature

### `SemVer`

- [X] Feature (:label: Minor)

### `Issues`

- Fixes #199

### `Checklist`

- [x] Lint and unit tests pass with my changes
- [x] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by ai** [comment]
@michael-ciniawsky can you give me access to the repo and npm package?

**Review by RyanZim — CHANGES_REQUESTED** [review]
Do Not Merge; this breaks linting, and I am 99% sure this does not function correctly.

**Comment by m4thieulavoie** [comment]
> Do Not Merge; this breaks linting, and I am 99% sure this does not function correctly.

Can you expand on that? Happy to adjust

**Comment by RyanZim** [comment]
Refs https://github.com/postcss/postcss/issues/1410

> Can you expand on that? Happy to adjust

Specifically, I'm not sure what this logic is doing, but I'm pretty sure it's not doing its intended purpose: https://github.com/michael-ciniawsky/postcss-load-config/blob/b03d1950e243f16cd3feb6d9948d35de37cefe37/src/plugins.js#L59-L61 Also, not sure what this `plugin.plugins` check is even there for. I tested last night, it wasn't broken as I expected, but I'm still not sure this logic is correct; would need to sit down and look closer to be sure.

**Comment by m4thieulavoie** [comment]
> Refs [postcss/postcss#1410](https://github.com/postcss/postcss/issues/1410)
> 
> > Can you expand on that? Happy to adjust
> 
> Specifically, I'm not sure what this logic is doing, but I'm pretty sure it's not doing its intended purpose:
> 
> https://github.com/michael-ciniawsky/postcss-load-config/blob/b03d1950e243f16cd3feb6d9948d35de37cefe37/src/plugins.js#L59-L61
> 
> Also, not sure what this `plugin.plugins` check is even there for. I tested last night, it wasn't broken as I expected, but I'm still not sure this logic is correct; would need to sit down and look closer to be sure.

Alright, sounds like I'll need to wait for you to come back to me with your conclusion. Please keep me posted, or feel free to scrap that PR with a proper fix if that's easier for you 👍

**Comment by ai** [comment]
We need a different way to fix https://github.com/michael-ciniawsky/postcss-load-config/pull/202

**Comment by m4thieulavoie** [comment]
https://github.com/michael-ciniawsky/postcss-load-config/pull/202 Seems to fix just that, closing

**Pull request closed without merging**
