### PR TITLE
Allow file extensions for .postcssrc

### PR DESCRIPTION
**Pull request by daltones**
## Proposed changes

This PR introduces support for config files `.postcssrc.json` or `.postcssrc.yaml` (alternatives for `.postcssrc`) and `.postcssrc.js` (alternative for `postcss.config.js`). This is done by just enabling `cosmiconfig`'s option `rcExtensions`.

YAML format seems like news, but in fact it was already supported in `.postcssrc` once it's a `cosmiconfig` default behavior.

Extensions `.json` and `.yaml` are very helpful for text editors to give the right syntax highlighting.

`.postcssrc.js` offers a standard base name and is preferred in cases when it's interesting to this file be a dot-file (eg: ESLint ignores dot-files by default and you don't want `.postcssrc.js` to be linted along with all other source js files).

This feature makes `postcss-load-config` consistent with other `cosmiconfig` based projects like [ESLint](https://github.com/eslint/eslint) and [Stylelint](https://github.com/stylelint/stylelint).

## Types of changes

- [ ] Bug (non-breaking change which fixes an issue)
- [X] Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature which changes existing functionality)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/michael-ciniawsky/postcss-load-config/blob/master/CONTRIBUTING.md) guide
- [X] Lint and unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective/works
- [X] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

## Further comments

I saw that there's some separated tests for different config filenames. But I didn't feel like it's necessary to add more tests since we're just using `cosmiconfig` in a trivial way. Resolving of various config files are already well tested by `cosmiconfig` itself.

### Reviewers: @michael-ciniawsky, @ertrzyiks

### CODE REVIEW

**Comment by GitCop** [comment]
:warning: Pull Request - Issues :warning:

 * Commit: 3b41a2f3ea14932841da1ad96421a33ad7ecb546
  * Your subject line is longer than 72 characters



---
This message was auto-generated by https://gitcop.com

**Comment by michael-ciniawsky** [comment]
@daltones Can you please provide an example of a config file using extensions ? :) What is your usecase ?

 cc @ai @ertrzyiks

**Comment by daltones** [comment]
@michael-ciniawsky Actually there's nothing new about the config itself. This PR is just adding support to recognize `.postcssrc` with extensions.

My usecase would be my text editor properly highlighting the config file. You see when I open `.postcssrc` in Atom Editor, it doesn't know that that's a JSON file. But it will know if I use a `.postcssrc.json`. And every other editor will too.

See also https://stylelint.io/user-guide/configuration/#loading-the-configuration-object and http://eslint.org/docs/user-guide/configuring#configuration-file-formats. Notice that ESLint actually deprecated `.eslintrc` (without extension) in favor of `.eslintrc.(json|js|yaml)`.

**Comment by michael-ciniawsky** [comment]
@daltones 😆 I got it totally wrong, I was thinking  of something like 

```js
module.exports = (ctx) => ({
   parser: ctx.fil.extname === '.sss' ? 'sugarss' : false,
   plugins: [...plugins],
   extends: 'Idiocrazy :)' 
})
```

should better have checked the cosmiconfig docs first 🙃

Agreed, I need to update it for postcss-load-options && postcss-load-plugins 
aswell and quickly test with all middlewares before release, so it likely will take until tomorrow 😛 

Could you add yourself as Collaborator to the README please so I can merge this one here?

**Comment by daltones** [comment]
@michael-ciniawsky Yeah, I already added myself as contributor in https://github.com/michael-ciniawsky/postcss-load-config/pull/68/commits/f159fa2619052603a19fd9c3a7ac6a05af7def2f

Thanks! 😄

**Comment by michael-ciniawsky** [comment]
@daltones Thx

**Pull request merged**
